EnterChatWeb/Models/File.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EnterChatWeb.Models
{
    public class File
    {
        public int ID { get; set; }
        public int? CompanyID { get; set; }
        public int? UserID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreationDate { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }

        public Company Company { get; set; }
        //public User User { get; set; }
        [NotMapped]
        public UserPlusWorkerModel UserPlusWorker { get; set; }
    }
}

EnterChatWeb/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EnterChatWeb.Models
{
    public class Note
    {
        public int ID { get; set; }
        public int? UserID { get; set; }
        public int? CompanyID { get; set; }
        public int? NoteCategoryID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreationDate { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите тему заметки!")]
        [StringLength(20, ErrorMessage = "Навзвание заметки не может быть больше 20 символов!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите текст заметки!")]
        [StringLength(250, ErrorMessage = "Текст заметки не может быть больше 250 символов!")]
        public string Text { get; set; }

        //public User User { get; set; }
        [NotMapped]
        public UserPlusWorkerModel UserPlusWorker { get; set; }
        public Company Company { get; set; }
        public NoteCategory NoteCategory { get; set; }
    }
}

EnterChatWeb/Models/Topic.cs
using EnterChatWeb.Models.ExtraModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EnterChatWeb.Models
{
    public class Topic
    {
        public int ID { get; set; }
        public int? CompanyID { get; set; }
        public int? UserID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime CreationDate { get; set; }
        public string Title { get; set; }

        public ICollection<TopicMessage> TopicMessages { get; set; }
        [NotMapped]
        public ICollection<WorkerChatMember> WorkerChatMembers { get; set; }
        public Company Company { get; set; }
        public User User { get; set; }
    }
}

EnterChatWeb/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EnterChatWeb.Data;
using EnterChatWeb.Models;
using EnterChatWeb.Models.ExtraModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EnterChatWeb.Controllers
{
    public class DataController : Controller
    {
        private EnterChatContext _context;
        private IHostingEnvironment _appEnvironment;

        public DataController(EnterChatContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _appEnvironment = hostingEnvironment;
        }

        [Authorize]
        public async Task<IActionResult> About()
        {
            int comp_id = Int32.Parse(HttpContext.User.FindFirst("CompanyID").Value);
            var company = await _context.Companies.FirstOrDefaultAsync(c => c.ID == comp_id);
            var departments = await _context.Departments.Where(d => d.CompanyID == comp_id).ToListAsync();
            foreach (Department dep in departments)
            {
                var workers = await _context.Workers.Where(x => x.DepartmentID == dep.ID).ToListAsync();
                List<UserPlusWorkerModel> userPlusWorkers = new List<UserPlusWorkerModel>();
                if (workers != null)
                {
                    foreach (Worker w in workers)
                    {
                        UserPlusWorkerModel userPlusWorkerModel = new UserPlusWorkerModel(w.FirstName, w.SecondName, w.InviteCode);
                        User user = await _context.Users.Where(u => u.WorkerID == w.ID).FirstOrDefaultAsync();
                        if (user != null)
                        {
                            userPlusWorkerModel.RegistrationDate = user.RegistrationDate;
                            userPlusWorkerModel.Email = user.Email;
                        }
                        userPlusWorkers.Add(userPlusWorkerModel);
                    }
                    dep.UserPlusWorkers = userPlusWorkers;
                }
            }
            company.Departments = departments;
            return View(company);
        }

        [Authorize(Policy = "OnlyForAdmin")]
        public async Task<IActionResult> AdminPanel()
        {
            int comp_id = Int32.Parse(HttpContext.User.FindFirst("CompanyID").Value);
            var deps = await _context.Departments.Where(d => d.CompanyID == comp_id).ToListAsync();
            //var workers = await _context.Workers.Where(x => x.CompanyID == comp_id).ToListAsync();
            foreach (Department dep in deps)
            {
                var workers = await _context.Workers.Where(x => x.DepartmentID == dep.ID).ToListAsync();
                List<UserPlusWorkerModel> userPlusWorkers = new List<UserPlusWorkerModel>();
                if (workers != null)
                {
                    foreach (Worker w in workers)
                    {
                        UserPlusWorkerModel userPlusWorkerModel = new UserPlusWorkerModel(w.FirstName, w.SecondName, w.InviteCode, w.ID);
                        User user = await _context.Users.Where(u => u.WorkerID == w.ID).FirstOrDefaultAsync();
                        if (user != null)
                        {
                            userPlusWorkerModel.RegistrationDate = user.RegistrationDate;
                            userPlusWorkerModel.Email = user.Email;
                        }
                        userPlusWorkers.Add(userPlusWorkerModel);
                    }
                    dep.UserPlusWorkers = userPlusWorkers;
                }

            }
            var company = await _context.Companies.FirstOrDefaultAsync(c => c.ID == comp_id);
            /*AdminPanelModel model = new AdminPanelModel();
            model.Company = company;
            model.Workers = workers;*/
            company.Departments = deps;
            return View(company);
        }

        [Authorize]
        public async Task<IActionResult> AccountPanel()
        {
            int user_id = Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            User user = await _context.Users.FirstOrDefaultAsync(u => u.ID == user_id);
            return View(user);
        }

        [Authorize]
        public async Task<IActionResult> EditUser(int? id)
        {
            if (id != null)
            {
                User user = await _context.Users.FirstOrDefaultAsync(u => u.ID == id);
                if (user != null)
                {
                    return View(user);
                }
            }
            return NotFound();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditUser(User user)
        {
            User user_db = await _context.Users.FirstOrDefaultAsync(u => u.ID == user.ID);
            if (user_db != null)
            {
                if (!String.IsNullOrEmpty(user.Login) && !String.IsNullOrEmpty(user.Email))
                {
                    user_db.Login = user.Login;
                    user_db.Email = user.Email;
                    await _context.SaveChangesAsync();
                    return RedirectToAction("AccountPanel");
                }
            }
            ModelState.AddModelError("", "Некорректные данные");
            return View(user);
        }

        [Authorize]
        public async Task<IActionResult> Files()
        {
            int comp_id = Int32.Parse(HttpContext.User.FindFirst("CompanyID").Value);
            var files = await _context.Files.Where(f => f.CompanyID == comp_id).ToListAsync();
            foreach (Models.File f in  files)
            {
                User user = await _context.Users.Where(w => w.ID == f.UserID).FirstOrDefaultAsync();
                Worker worker = await _context.Workers.Where(w => w.ID == user.WorkerID).FirstOrDefaultAsync();
                UserPlusWorkerModel model = new UserPlusWorkerModel(worker.FirstName, worker.SecondName,
                    user.Email);
                f.UserPlusWorker = model;
            }
            return View(files);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                // путь к папке Files
                string path = "/files/" + uploadedFile.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

                int comp_id = Int32.Parse(HttpContext.User.FindFirst("CompanyID").Value);
                int user_id = Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

                Models.File file = new Models.File
                {
                    CompanyID = comp_id,
                    UserID = user_id,
                    Name = uploadedFile.FileName,
                    Link = path,
                    CreationDate = DateTime.Now
                };

                _context.Files.Add(file);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Files");
        }

        [Authorize]
        [ActionName("DeleteFile")]
        public IActionResult ConfirmDeleteFile(int? id)
        {
            if (id != null)
            {
                Models.File file = _context.Files.FirstOrDefault(w => w.ID == id);
                if (file != null)
                {
                    return View(file);
                }
            }
            return NotFound();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteFile(int? id)
        {
            if (id != null)
            {
                Models.File file = await _context.Files.FirstOrDefaultAsync(f => f.ID == id);
                if (file != null)
                {
                    _context.Files.Remove(file);
                    await _context.SaveChangesAsync();
                    string path = "/files/" + file.Name;
                    if (System.IO.File.Exists(_appEnvironment.WebRootPath + path))
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath + path);
                    }
                    return RedirectToAction("Files");
                }
            }
            return NotFound();
        }


        [Authorize]
        public async Task<IActionResult> GroupChat()
        {
            int comp_id = Int32.Parse(HttpContext.User.FindFirst("CompanyID").Value);
            int user_id = Int32.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var messages = await _context.GroupChatMessages.Where(m => m.CompanyID == comp_id).ToListAsync();
            User user = await _context.Users.Where(u => u.ID == user_id).FirstOrDefaultAsync();
            Worker worker = await _context.Workers.Where(w => w.ID == user.WorkerID).FirstOrDefaultAsync();
            Department department = await _context.Departments.Where(d => d.ID == worker.DepartmentID).FirstOrDefaultAsync();

            foreach (GroupChatMessage message in messages)
            {
                User _user = await _context.Users.Where(u => u.ID == message.UserID).FirstOrDefaultAsync();
                Worker _worker = await _context.Workers.Where(w => w.ID == _user.WorkerID).FirstOrDefaultAsync();
                UserPlusWorkerModel _model = new UserPlusWorkerModel(_worker.FirstName, _worker.SecondName,
                    _user.Email);

EnterChatWeb/Views/Data/About.cshtml
@model EnterChatWeb.Models.Company

<head>
    <title>О компании</title>
</head>
<nav class="navbar page-header">
    <div class="container-fluid">
        <div class="navbar-header">
            <h3>Информация о компании</h3>
        </div>
    </div>
</nav>
<div class="first-head">

    <div class="container-fluid info-card">
        <div class="container-fluid info-shit">
            <h2>Информация</h2>
            <p>Название компании: @Model.Title</p>
            <p>Адрес корпоративной почты: @Model.WorkEmail</p>
            <p>Дата регистрации: @Model.CreationDate</p>
        </div>
    </div>
</div>

<div class="container-fluid info-card">
    <div class="container-fluid info-shit">

        <h2>
            Список отделов и работников
        </h2>
        <div class="container-fluid">
            @foreach (var item in Model.Departments)
            {
                <h3>@item.Title <small>Привилегии администратора: @item.StringStatus</small></h3>
                    @foreach (var worker in item.UserPlusWorkers)
                    {
                        <div class="list-item-worker">
                            <h4>@worker.FirstName @worker.SecondName <span class="span-email">@worker.Email</span>

                            </h4>
                            @if (@worker.Email != null && @worker.RegistrationDate != null)
                            {
                                <h5>Зарегистрировался: @worker.RegistrationDate</h5>
                            }
                            else
                            {
                                <h5>Ещё не активирован</h5>

                            }

                            @if (worker.InviteCode == null)
                            {
                                <p>Создатель хаба</p>
                            }
                           
                        </div>

                    }
            }
        </div>
    </div>
</div>

EnterChatWeb/Views/Data/AccountPanel.cshtml
@model EnterChatWeb.Models.User

<head>
    <title>Аккаунт пользователя</title>
</head>

<nav class="navbar page-header">
    <div class="container-fluid">
        <div class="navbar-header">
            <h3>Управление аккаунтом</h3>
        </div>
        <ul class="nav navbar-nav navbar-right" style="margin-right:260px; margin-top:10px;">
            <li>
                <a id="my-main-button" asp-action="Logout" asp-controller="Account">
                    <span><i class="material-icons">power_settings_new</i></span>
                </a>
            </li>
        </ul>
    </div>
</nav>

<div class="first-head">
    <div class="container-fluid info-card" style="padding-top: 10px; padding-bottom: 10px;">
        <p>Логин: @Model.Login</p>
        <p>Почта: @Model.Email</p>
        <p>Дата регистрации: @Model.RegistrationDate</p>

        <p><a class="btn btn-primary" asp-controller="Data" asp-action="EditUser" 
              asp-route-id="@Model.ID">Изменить данные</a></p>
    </div>
</div>

EnterChatWeb/Views/Data/AddChatMember.cshtml
@model EnterChatWeb.Models.ExtraModel.EditChatMemberExtraModel
@{
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Добавление участника</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<form asp-action="AddChatMember" id="login-form" method="post" asp-controller="Data">
    <div asp-validation-summary="All"></div>
    <div class="container text-center">

        <h4 style="margin-top:40px;">Добавление сотрудника в чат "@Model.Title"</h4>

        <div>
            <select asp-for="ID" class="form-control">
                @foreach (var mem in Model.WorkerChatMembers)
                {
                    <option value="@mem.ID">@mem.FullName</option>
                }
            </select>
        </div>
        <input asp-for="@Model.TopicID" type="hidden" />
        <div>
            <input id="action-submit" type="submit" value="Добавить в чат"/>
        </div>
    </div>
</form>

EnterChatWeb/Views/Data/AddDep.cshtml
@model EnterChatWeb.Models.Department
@{
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>добавить отдел</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<form asp-action="AddDep" id="login-form" method="post" asp-controller="Data">
    <div asp-validation-summary="All"></div>
    <div class="container text-center">
        <div>
            <input type="text" asp-for="Title" placeholder="Название" />
        </div>
        <div>
            <label asp-for="Status" class="control-label">Привилегии администратора</label>
            <input asp-for="Status" type="checkbox" value="Status" />
        </div>
        <div>
            <input id="action-submit" type="submit" value="Добавить"/>
        </div>
    </div>
</form>

EnterChatWeb/Views/Data/AddWorker.cshtml
@model EnterChatWeb.Models.ExtraModel.WorkerPlusDepsList;
@using System.Security.Claims

@{
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Добавить сотрудника</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<form asp-action="AddWorker" id="login-form" method="post" asp-controller="Data">
    <div asp-validation-summary="All"></div>
    <div class="container text-center">
        <div>
            <input type="text" asp-for="FirstName" placeholder="Имя"/>
        </div>
        <div>
            <input type="text" asp-for="SecondName" placeholder="Фамилия" />
        </div>
        <div>
            <input type="text" asp-for="InviteCode" placeholder="Пригласительный код" />
        </div>
        <div>
            <select asp-for="DepartmentID" class="form-control">
                @foreach (var dep in Model.Departments)
                {
                    <option value="@dep.ID">@dep.Title</option>
                }
            </select>
        </div>
        <div>
            <input id="action-submit" type="submit" value="Добавить" />
        </div>
    </div>
</form>

EnterChatWeb/Views/Data/Delete.cshtml
@model EnterChatWeb.Models.Worker
@{ 
    Layout = null;
}
<div>
    <dl class="dl-horizontal">
        <dt>Имя</dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>Фамилия</dt>
        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>
    </dl>

    <div>
        <form asp-controller="Data" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>

</div>

EnterChatWeb/Views/Data/DeleteChatMember.cshtml
@model EnterChatWeb.Models.ExtraModel.EditChatMemberExtraModel
@{ 
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Удаление участника</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<form asp-action="DeleteChatMember" id="login-form" method="post" asp-controller="Data">
    <div asp-validation-summary="All"></div>
    <div class="container text-center">

        <h4 style="margin-top:40px;">Удаление сотрудника из чата "@Model.Title"</h4>

        <div>
            <select asp-for="ID" class="form-control">
                @foreach (var mem in Model.WorkerChatMembers)
                {
                    <option value="@mem.ID">@mem.FullName</option>
                }
            </select>
        </div>
        <input asp-for="@Model.TopicID" type="hidden" />
        <div>
            <input id="action-submit" type="submit" value="Удалить из чата" />
        </div>
    </div>
</form>

EnterChatWeb/Views/Data/DeleteNote.cshtml
@model EnterChatWeb.Models.Note
@{
    Layout = null;
}
<div>
    <dl class="dl-horizontal">
        <dt>Тема</dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>Текст</dt>
        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>Дата создания</dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>

    <div>
        <form asp-controller="Data" asp-action="DeleteNote" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>

</div>

EnterChatWeb/Views/Data/DeleteWorker.cshtml
@model EnterChatWeb.Models.Worker
@{ 
    Layout = null;
}
<div>
    <dl class="dl-horizontal">
        <dt>Имя</dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>Фамилия</dt>
        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>
    </dl>

    <div>
        <form asp-controller="Data" asp-action="DeleteWorker" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>

</div>

EnterChatWeb/Views/Data/EditNote.cshtml
@model EnterChatWeb.Models.ExtraModel.NotePlusCategoriesList

@{
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Редактирование заметки</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<form asp-action="EditNote" id="login-form" method="post" asp-controller="Data" asp-route-id="@Model.ID">
    <div asp-validation-summary="All"></div>
    <div class="container text-center">
        <div>
            <input type="text" asp-for="Title" placeholder="Тема"/>
        </div>
        <div class="form-group">
            <textarea class="form-control" rows="5" asp-for="Text" placeholder="Текст заметки"></textarea>
        </div>
        <div>
            <select asp-for="NoteCategoryID" class="form-control">
                @foreach (var cat in Model.NoteCategories)
                {
                    <option value="@cat.ID">@cat.Title</option>
                }
            </select>
        </div>
        <div>
            <input id="action-submit" type="submit" value="Сохранить" />
        </div>
   </div>
</form>

EnterChatWeb/Views/Data/EditTopicTitle.cshtml
@model EnterChatWeb.Models.Topic

@{ 
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Изменить название беседы</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<form asp-action="EditTopicTitle" id="login-form" method="post" asp-controller="Data">
    <div asp-validation-summary="All"></div>
    <div class="container text-center">
        <div>
            <input type="text" asp-for="Title" placeholder="Название беседы" />
        </div>
        <div>
            <input id="action-submit" type="submit" value="Изменить" />
        </div>
    </div>
</form>

EnterChatWeb/Views/Data/EditWorker.cshtml
@model EnterChatWeb.Models.ExtraModel.WorkerPlusDepsList
@{
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Редактирование данных сотрудника</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<form asp-action="EditWorker" id="login-form" asp-controller="Data" asp-route-id="@Model.ID">
    <div asp-validation-summary="All"></div>
    <div class="container text-center">
        <div>
            <input type="text" asp-for="FirstName" placeholder="Имя" />
        </div>
        <div>
            <input type="text" asp-for="SecondName" placeholder="Фамилия" />
        </div>
        <div>
            <input type="text" asp-for="InviteCode" placeholder="Пригласительный код" />
        </div>
        <div>
            <select asp-for="DepartmentID" class="form-control">
                @foreach (var dep in Model.Departments)
                {
                    <option value="@dep.ID">@dep.Title</option>
                }
            </select>
        </div>
        <div>
            <input id="action-submit" type="submit" value="Сохранить"/>
        </div>
   </div>
</form>

EnterChatWeb/Views/Data/Notes.cshtml
@model IEnumerable<EnterChatWeb.Models.NoteCategory>

<head>
    <title>Заметки</title>
</head>

<nav class="navbar page-header">
    <div class="container-fluid">
        <div class="navbar-header">
            <h3>Заметки компании</h3>
        </div>
        <ul class="nav navbar-nav navbar-right" style="margin-right:260px; margin-top:10px;">
            <li class="dropdown">
                <a class="dropdown-toggle" id="my-toggle" data-toggle="dropdown" href="#">
                    <span class="glyphicon glyphicon-option-vertical"></span>
                </a>
                <ul class="dropdown-menu">
                    @if (Model.Count() > 0)
                    {
                        <li><a asp-action="AddNote" class="main-menu-list-item">Добавить заметку</a></li>
                    }
                    <li><a asp-action="AddNoteCategory" class="main-menu-list-item">Добавить категорию</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

<div class="first-head">
    <div class="container-fluid info-card" style="padding-bottom: 10px">
        <div class="grid-container">
            @foreach (NoteCategory noteCategory in Model)
            {
            <div>
            <h3>@noteCategory.Title (@noteCategory.Notes.Count()):</h3>

                @foreach (var note in noteCategory.Notes)
                {

                <div class="list-item-note">
                    <h4>@note.Title</h4>
                    <p>@note.Text</p>
                    <p>Создан: @note.CreationDate</p>
                    <p>Автор: @note.UserPlusWorker.FirstName @note.UserPlusWorker.SecondName @note.UserPlusWorker.Email</p>
                    <p>Отдел: @note.UserPlusWorker.DepartmentName</p>
                    <a asp-action="EditNote" id="active-link" asp-controller="Data" asp-route-id="@note.ID">
                    <span><i class="material-icons">edit</i></span></a>
                    <a asp-action="DeleteNote" id="active-link" asp-controller="Data" asp-route-id="@note.ID">
                    <span><i class="material-icons">highlight_off</i></span></a>
                </div>
                }
            </div>
    }
            </div>
        </div>
</div>

EnterChatWeb/Views/Data/Topics.cshtml
@model IEnumerable<EnterChatWeb.Models.Topic>
@using System.Security.Claims
<head>
    <title>Обсуждения</title>
</head>

<nav class="navbar page-header">
<div class="container-fluid">
    <div class="navbar-header">
        <h3>Обсуждения компании</h3>
    </div>
    <ul class="nav navbar-nav navbar-right" style="margin-right:260px; margin-top:10px;">
        <li><a id="my-main-button" asp-action="AddTopic" asp-controller="Data">
            <span><i class="material-icons">add</i></span></a></li>
    </ul>
</div>
</nav>

<div class="first-head">
    <div class="container-fluid info-card">
        <div class="container-fluid info-shit" style="padding-top: 10px;">
    @foreach (Topic topic in Model)
    {
        <div class="list-item-note">
            <h4><a asp-action="TopicChat" id="active-link" asp-controller="Data" asp-route-id="@topic.ID">@topic.Title</a></h4>
            <div style="display:inline">
                <p style="display:inline-block">Участники: </p>
                @foreach (var member in topic.WorkerChatMembers)
                {
                    <p style="display:inline-block">[@member.FullName] </p>
                }
            </div>

            <p>Создан: @topic.CreationDate</p>
            @if (Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value) == topic.UserID)
            {
                <a asp-action="EditTopicTitle" id="active-link" asp-controller="Data" asp-route-id="@topic.ID">
                <span><i class="material-icons">edit</i></span></a>
                <a asp-action="DeleteTopic" id="active-link" asp-controller="Data" asp-route-id="@topic.ID">
                <span><i class="material-icons">highlight_off</i></span></a>
                <a asp-action="DeleteChatMember" id="active-link" asp-controller="Data" asp-route-id="@topic.ID">
                <span><i class="material-icons">person_outline</i></span></a>
                <a asp-action="AddChatMember" id="active-link" asp-controller="Data" asp-route-id="@topic.ID">
                <span><i class="material-icons">person_add</i></span></a>
            }
            else
            {
                <a asp-action="LeaveTopicChat" asp-controller="Data" asp-route-id="@topic.ID">
                    <span><i id="active-link" class="material-icons">power_settings_new</i></span></a>
            }
        </div>
    }
            </div>
</div>
</div>